import * as glMatrix from './gl-matrix/gl-matrix.js';
declare var glm: any;
declare const vec2: any;
declare const vec3: any;
declare const vec4: any;
declare const mat4: any;
declare const glcanvas: HTMLCanvasElement;
declare const gl: WebGL2RenderingContext;
declare const ct: CanvasRenderingContext2D;
export { gl, glm, glMatrix, vec2, vec3, vec4, mat4, ct, glcanvas };
